# OpenAL Soft Configuration File (alsoft.ini)
#
# Place this file in the same directory as halo.exe 
# to configure OpenAL Soft 3D spatialization, HRTF, speaker layouts, and resamplers.
# For full options reference, visit: https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample

[general]
channels = stereo
stereo-mode = headphones
frequency = 44100
stereo-encoding = hrtf
hrtf-mode = full
periods = 3
period_size = 128
sample-type=float32